const express = require('express');
const cors = require('cors');
const axios = require('axios');
const YTMusic = require('ytmusic-api');
const path = require('path');
const compression = require('compression');
const rateLimit = require('express-rate-limit');
const fs = require('fs');
const { execFile } = require('child_process');
require('dotenv').config();

const app = express();
const port = process.env.PORT || 5200;

app.use(compression());

// Restricted CORS configuration for production security
const allowedOrigins = ['https://app.musicidl.web.id', 'https://musicidl.web.id', 'http://localhost:5200', 'http://localhost:5173', 'http://43.153.205.18:5200', 'http://43.153.205.18'];
app.use(cors({
    origin: function (origin, callback) {
        if (!origin || allowedOrigins.indexOf(origin) !== -1) {
            callback(null, true);
        } else {
            callback(new Error('Not allowed by CORS'));
        }
    }
}));

app.use(express.json());

// Trust Proxy for accurate IP on VPS
app.set('trust proxy', 1);

// General Rate Limiter to prevent API abuse/spam
const apiLimiter = rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 200,
    message: { error: 'TOO_MANY_REQUESTS', message: 'Terlalu banyak permintaan dari IP ini, silakan coba lagi nanti.' }
});
app.use('/api/', apiLimiter);

// Logger
app.use((req, res, next) => {
    console.log(`${req.method} ${req.url}`);
    next();
});

const SITE_URL = 'https://app.musicidl.web.id';

app.get('/robots.txt', (req, res) => {
    res.type('text/plain').send(`User-agent: *
Allow: /
Sitemap: ${SITE_URL}/sitemap.xml
`);
});

app.get('/sitemap.xml', (req, res) => {
    res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE_URL}/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>
`);
});

const ytmusic = new YTMusic();

async function initYT() {
    try {
        await ytmusic.initialize();
        console.log('YTMusic initialized');
    } catch (err) {
        console.error('Failed to initialize YTMusic:', err.message);
    }
}

initYT();

// Serve Static Files (React Build)
app.use(express.static(path.join(__dirname, 'dist'), {
    maxAge: '7d',
    etag: true,
    lastModified: true,
    setHeaders: (res, path) => {
        if (path.endsWith('.html')) {
            res.setHeader('Cache-Control', 'no-cache');
        } else if (path.match(/\.(js|css|woff2|svg|png|jpg|jpeg)$/)) {
            res.setHeader('Cache-Control', 'public, max-age=604800, immutable');
        }
    }
}));

// Helper to run python music_dl_engine script
const engineScriptPath = path.join(__dirname, 'engine', 'music_dl.py');
const outputDir = path.join(__dirname, 'output_music');

if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

function runEngineDownload(url) {
    return new Promise((resolve, reject) => {
        const pythonCmd = '/home/ubuntu/music_dl_venv/bin/python3';
        execFile(pythonCmd, [engineScriptPath, url], { cwd: __dirname }, (error, stdout, stderr) => {
            if (error) {
                console.error('Engine error stderr:', stderr);
                return reject(error);
            }

            try {
                const files = fs.readdirSync(outputDir).filter(f => f.endsWith('.mp3'));
                if (files.length === 0) {
                    return reject(new Error('No MP3 file generated by engine'));
                }

                const latestFile = files
                    .map(f => ({ name: f, time: fs.statSync(path.join(outputDir, f)).mtimeMs }))
                    .sort((a, b) => b.time - a.time)[0].name;

                const fullPath = path.join(outputDir, latestFile);
                resolve({ filePath: fullPath, fileName: latestFile });
            } catch (err) {
                reject(err);
            }
        });
    });
}

// API Routes
app.get('/api/search', async (req, res) => {
    const { q } = req.query;
    if (!q) return res.status(400).json({ error: 'Query parameter q is required' });

    if (q.startsWith('http://') || q.startsWith('https://')) {
        if (q.includes('music.apple.com') || q.includes('youtube.com') || q.includes('youtu.be')) {
            return res.json([{ type: 'URL_REDIRECT', url: q }]);
        }
    }

    try {
        const results = await ytmusic.search(q);
        const filtered = results.filter(item => item.type === 'SONG' || item.type === 'VIDEO');
        res.json(filtered);
    } catch (err) {
        console.error('Search error:', err);
        res.status(500).json({ error: 'Failed to search' });
    }
});

app.get('/api/external-info', async (req, res) => {
    const { videoId } = req.query;
    if (!videoId) return res.status(400).json({ error: 'Video ID is required' });

    try {
        return res.json({
            status: true,
            title: `YouTube Track (${videoId})`,
            channel: 'YouTube Artist',
            duration_sec: 180,
            bitrate: '320kbps',
            filesize: 8 * 1024 * 1024,
            thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
            download_url: `/api/engine-download?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${videoId}`)}`
        });
    } catch (err) {
        res.status(500).json({ error: 'Failed to fetch metadata' });
    }
});

app.get('/api/download', async (req, res) => {
    const { v, url } = req.query;
    let targetUrl = url;

    if (v && !targetUrl) {
        targetUrl = `https://www.youtube.com/watch?v=${v}`;
    }

    if (!targetUrl) return res.status(400).json({ error: 'Video ID or URL is required' });

    return res.json({
        download_url: `/api/engine-download?url=${encodeURIComponent(targetUrl)}`,
        title: 'Music Download',
        thumbnail: '',
        channel: 'Music IDL Engine',
        status: true
    });
});

function getYoutubeVideoInfo(url, videoId) {
    return new Promise((resolve) => {
        const ytdlpPath = '/home/ubuntu/music_dl_venv/bin/yt-dlp';
        execFile(ytdlpPath, [
            '-j',
            '--proxy', 'socks5://127.0.0.1:40000',
            '--cookies', '/home/ubuntu/cookies.txt',
            url
        ], (error, stdout) => {
            const defaultTitle = videoId && videoId.length === 11 ? `YouTube Track ${videoId}` : 'YouTube Track';
            if (error) {
                console.error('Info extract error:', error.message);
                return resolve({ title: defaultTitle, uploader: 'Music IDL Engine', thumbnail: '' });
            }
            try {
                const info = JSON.parse(stdout);
                resolve({
                    title: info.title || defaultTitle,
                    uploader: info.uploader || info.artist || 'Music IDL Engine',
                    thumbnail: info.thumbnail || ''
                });
            } catch (e) {
                resolve({ title: defaultTitle, uploader: 'Music IDL Engine', thumbnail: '' });
            }
        });
    });
}

app.get('/api/url-info', async (req, res) => {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: 'URL is required' });

    const regExp = /^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/|shorts\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*/;
    const match = url.match(regExp);
    const videoId = (match && match[1].length === 11) ? match[1] : `song-${Date.now()}`;

    const info = await getYoutubeVideoInfo(url, videoId);

    return res.json({
        videoId: videoId,
        name: info.title,
        artist: { name: info.uploader },
        thumbnails: [{ url: info.thumbnail || (videoId.length === 11 ? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg` : 'https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/3d/0d/1d/3d0d1d23-2345-2345-2345-234523452345/source/512x512bb.jpg'), width: 480, height: 360 }],
        type: 'SONG',
        isDirect: true,
        externalData: {
            download_url: `/api/engine-download?url=${encodeURIComponent(url)}`,
            title: info.title,
            channel: info.uploader,
            thumbnail: info.thumbnail || (videoId.length === 11 ? `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg` : ''),
            status: true,
            bitrate: '320kbps',
            filesize: 8 * 1024 * 1024
        }
    });
});

app.get('/api/fallback-download', async (req, res) => {
    const { videoId } = req.query;
    if (!videoId) return res.status(400).json({ error: 'Video ID is required' });

    const targetUrl = `https://www.youtube.com/watch?v=${videoId}`;
    return res.json({
        status: true,
        download_url: `/api/engine-download?url=${encodeURIComponent(targetUrl)}`,
        title: 'YouTube Track',
        channel: 'Artist',
        thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
    });
});

app.get('/api/engine-download', async (req, res) => {
    const { url } = req.query;
    if (!url) return res.status(400).json({ error: 'URL is required' });

    console.log(`[Engine] Mulai mengunduh via music-idl-engine: ${url}`);
    try {
        const { filePath, fileName } = await runEngineDownload(url);

        res.download(filePath, fileName, (err) => {
            if (err) {
                console.error('File send error:', err.message);
            }
            fs.unlink(filePath, () => {});
        });
    } catch (err) {
        console.error('Engine download process failed:', err.message);
        if (!res.headersSent) {
            res.status(500).json({ error: 'Gagal mengunduh musik dari engine.' });
        }
    }
});

app.get('/api/proxy-download', async (req, res) => {
    const { url, filename, title, artist, image, album } = req.query;
    if (!url) return res.status(400).json({ error: 'URL is required' });

    if (url.startsWith('/api/engine-download')) {
        const targetUrl = new URL(url, `http://${req.headers.host}`).searchParams.get('url');
        console.log(`[Engine Proxy] Forwarding to engine-download for: ${targetUrl}`);
        try {
            const { filePath, fileName } = await runEngineDownload(targetUrl);

            return res.download(filePath, `${title || fileName}.mp3`, (err) => {
                if (err) {
                    console.error('File send error:', err.message);
                }
                fs.unlink(filePath, () => {});
            });
        } catch (err) {
            console.error('Engine proxy download process failed:', err.message);
            if (!res.headersSent) {
                return res.status(500).json({ error: 'Gagal mengunduh musik dari engine.' });
            }
        }
    }

    try {
        const response = await axios({
            method: 'get',
            url: url,
            responseType: 'stream',
            timeout: 120000
        });

        const cleanFilename = (filename || 'audio.mp3').replace(/[/\\?%*:|"<>]/g, '-');
        res.setHeader('Content-Disposition', `attachment; filename="${cleanFilename}"`);
        res.setHeader('Content-Type', 'audio/mpeg');
        response.data.pipe(res);
    } catch (err) {
        console.error('Proxy error:', err.message);
        if (!res.headersSent) res.status(500).send(`Gagal mengunduh: ${err.message}`);
    }
});

// Error Handling for Uncaught Exceptions to prevent crash
process.on('uncaughtException', (err) => {
    console.error('Uncaught Exception:', err);
});

process.on('unhandledRejection', (reason, promise) => {
    console.error('Unhandled Rejection at:', promise, 'reason:', reason);
});

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});
